generation_config:
    do_sample: false
    temperature: 1
    top_p: 1

dola_generation_config:
    dola_layers: low
    do_sample: false
    temperature: 1
    top_p: 1
    
model_id: "meta-llama/Llama-3.1-8B-Instruct"
batch_size: 32
seed: 42
